---
#
#Use "§" as a color symbol
#Use "\n" to go to the next line
#The title of the menu
Title: "§lGamemodeUI"

#Message when changing gamemode to creative
msg-creative: "Changing Gamemode To Creatvie"

#Message when changing gamemode to Survival
msg-survival: "Changing Gamemode To survival"

#Message when changing gamemode to Adventure
msg-adventure: "Changing Gamemode To Adventure"

#Message when changing gamemode to spectator
msg-spectator: "Changing Gamemode To Spectator"

#Message when player didn't have perm
msg-no-perm: "§cYou didn't have permission to use this command!"
#
...
